// **********************************************
// Info Disp Provv
// Project : Cfa
// **********************************************

import com.progamma.is.*;
import com.progamma.*;
import com.progamma.idre.*;
import com.progamma.doc.*;

import java.io.*;
import java.util.*;
import java.sql.*;


public final class InfoDispProvv extends MyWebForm implements Serializable
{  
  MyWebEntryPoint MainFrm;
  
  // Frame constant definitions
  private static int PFL_INFODISPPROV_VARPROVTOT = 0;
  private static int PFL_INFODISPPROV_VARPROVPURO = 1;
  private static int PFL_INFODISPPROV_VARPROVESI = 2;
  private static int PFL_INFODISPPROV_VARPROVSTN = 3;
  private static int PFL_INFODISPPROV_VARPROVCASSA = 4;
  private static int PFL_INFODISPPROV_STANZATTTOT = 5;
  private static int PFL_INFODISPPROV_STANZATTPURO = 6;
  private static int PFL_INFODISPPROV_STANZATTESI = 7;
  private static int PFL_INFODISPPROV_STANZATTSTN = 8;
  private static int PFL_INFODISPPROV_STANZATTCASS = 9;
  private static int PFL_INFODISPPROV_DISPTOT = 10;
  private static int PFL_INFODISPPROV_SUREISCRIZIO = 11;
  private static int PFL_INFODISPPROV_DISPESI = 12;
  private static int PFL_INFODISPPROV_DISPSTN = 13;
  private static int PFL_INFODISPPROV_DISPCASSA = 14;
  private static int PFL_INFODISPPROV_ETICHETTCOMP = 15;
  private static int PFL_INFODISPPROV_ETICHETOTALE = 16;
  private static int PFL_INFODISPPROV_ETICHETCASSA = 17;
  private static int PFL_INFODISPPROV_ETICREIDAESI = 18;
  private static int PFL_INFODISPPROV_ETICREIDASTA = 19;

  private static int PPQRY_PARAMETRI505 = 0;


  IDPanel PAN_INFODISPPROV;

  // Definition of Global Variables

 
  // **********************************************
  // Inizializzatore tabelle IMDB di form
  // **********************************************
  public static void ImdbInit(IMDBObj IMDB)
  {
    Init_TBL_PARAMETRI501(IMDB);
    //
    //
    Init_PQRY_PARAMETRI505(IMDB);
    Init_PQRY_PARAMETRI505_RS(IMDB);
  }

  // IMDB DDL Procedures
  private static void Init_TBL_PARAMETRI501(IMDBObj IMDB)
  {
    IMDB.set_TblNumField(IMDBDef7.TBL_PARAMETRI501, 24);
    IMDB.set_TblCode(IMDBDef7.TBL_PARAMETRI501, "TBL_PARAMETRI501");
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARAMESERCIZ, "PARAMESERCIZ");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARAMESERCIZ,1,4,0);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARAMSTANATT, "PARAMSTANATT");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARAMSTANATT,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATTESI, "PARSTAATTESI");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATTESI,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATTSTN, "PARSTAATTSTN");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATTSTN,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATTCAS, "PARSTAATTCAS");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATTCAS,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARAMDISPONI, "PARAMDISPONI");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARAMDISPONI,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARAMDISPESI, "PARAMDISPESI");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARAMDISPESI,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARAMDISPSTN, "PARAMDISPSTN");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARAMDISPSTN,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARADISPCASS, "PARADISPCASS");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARADISPCASS,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARVARPROTOT, "PARVARPROTOT");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARVARPROTOT,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARVARPROPUR, "PARVARPROPUR");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARVARPROPUR,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARVARPROESI, "PARVARPROESI");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARVARPROESI,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARVARPROSTN, "PARVARPROSTN");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARVARPROSTN,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARVARPROCAS, "PARVARPROCAS");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARVARPROCAS,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATTOPR, "PARSTAATTOPR");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATTOPR,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATPUPR, "PARSTAATPUPR");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATPUPR,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATESPR, "PARSTAATESPR");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATESPR,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATSTPR, "PARSTAATSTPR");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATSTPR,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATCAPR, "PARSTAATCAPR");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARSTAATCAPR,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARDISTOTPRO, "PARDISTOTPRO");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARDISTOTPRO,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARDISPURPRO, "PARDISPURPRO");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARDISPURPRO,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARDISESIPRO, "PARDISESIPRO");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARDISESIPRO,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARDISSTNPRO, "PARDISSTNPRO");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARDISSTNPRO,3,14,2);
    IMDB.set_FldCode(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARDISCASPRO, "PARDISCASPRO");
    IMDB.SetFldParams(IMDBDef7.TBL_PARAMETRI501,IMDBDef7.FLD_PARAMETRI501_PARDISCASPRO,3,14,2);
    IMDB.TblAddNew(IMDBDef7.TBL_PARAMETRI501, 0);
  }

  private static void Init_PQRY_PARAMETRI505(IMDBObj IMDB)
  {
    IMDB.set_TblNumField(IMDBDef17.PQRY_PARAMETRI505, 15);
    IMDB.set_TblCode(IMDBDef17.PQRY_PARAMETRI505, "PQRY_PARAMETRI505");
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECVARPROTOT, "RECVARPROTOT");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECVARPROTOT,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECVARPROPUR, "RECVARPROPUR");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECVARPROPUR,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECVARPROESI, "RECVARPROESI");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECVARPROESI,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECVARPROSTN, "RECVARPROSTN");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECVARPROSTN,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECVARPROCAS, "RECVARPROCAS");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECVARPROCAS,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECSTAATTOPR, "RECSTAATTOPR");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECSTAATTOPR,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECSTAATPUPR, "RECSTAATPUPR");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECSTAATPUPR,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECSTAATESPR, "RECSTAATESPR");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECSTAATESPR,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECSTAATSTPR, "RECSTAATSTPR");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECSTAATSTPR,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECSTAATCAPR, "RECSTAATCAPR");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECSTAATCAPR,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECDISTOTPRO, "RECDISTOTPRO");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECDISTOTPRO,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECDISPURPRO, "RECDISPURPRO");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECDISPURPRO,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECDISESIPRO, "RECDISESIPRO");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECDISESIPRO,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECDISSTNPRO, "RECDISSTNPRO");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECDISSTNPRO,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECDISCASPRO, "RECDISCASPRO");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505,IMDBDef17.PQSL_PARAMETRI505_RECDISCASPRO,3,14,2);
    IMDB.TblAddNew(IMDBDef17.PQRY_PARAMETRI505, 0);
  }

  private static void Init_PQRY_PARAMETRI505_RS(IMDBObj IMDB)
  {
    IMDB.set_TblNumField(IMDBDef17.PQRY_PARAMETRI505_RS, 15);
    IMDB.set_TblCode(IMDBDef17.PQRY_PARAMETRI505_RS, "PQRY_PARAMETRI505_RS");
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECVARPROTOT, "RECVARPROTOT");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECVARPROTOT,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECVARPROPUR, "RECVARPROPUR");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECVARPROPUR,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECVARPROESI, "RECVARPROESI");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECVARPROESI,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECVARPROSTN, "RECVARPROSTN");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECVARPROSTN,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECVARPROCAS, "RECVARPROCAS");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECVARPROCAS,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECSTAATTOPR, "RECSTAATTOPR");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECSTAATTOPR,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECSTAATPUPR, "RECSTAATPUPR");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECSTAATPUPR,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECSTAATESPR, "RECSTAATESPR");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECSTAATESPR,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECSTAATSTPR, "RECSTAATSTPR");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECSTAATSTPR,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECSTAATCAPR, "RECSTAATCAPR");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECSTAATCAPR,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECDISTOTPRO, "RECDISTOTPRO");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECDISTOTPRO,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECDISPURPRO, "RECDISPURPRO");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECDISPURPRO,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECDISESIPRO, "RECDISESIPRO");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECDISESIPRO,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECDISSTNPRO, "RECDISSTNPRO");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECDISSTNPRO,3,14,2);
    IMDB.set_FldCode(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECDISCASPRO, "RECDISCASPRO");
    IMDB.SetFldParams(IMDBDef17.PQRY_PARAMETRI505_RS,IMDBDef17.PQSL_PARAMETRI505_RECDISCASPRO,3,14,2);
  }



  // **********************************************
  // Costruttore per form multiple
  // **********************************************
  public InfoDispProvv(MyWebEntryPoint w, IMDBObj imdb)
  {
    //
    SetMainFrm(w,imdb);
  }

  // **********************************************
  // Funzione chiamata su form multipla
  // durante l'inizializzazione
  // **********************************************
  public void SetMainFrm(WebEntryPoint w, IMDBObj i)
  {
    // Sono una form multipla, duplico IMDB
    IMDB = new IMDBObj();
    IMDB.set_DBSize(w.IwImdb.IMDB.DBSize());
    ImdbInit(IMDB);
    IMDB.SetMaster(w.IwImdb.IMDB);
    super.SetMainFrm(w,i);
  }
  public void SetSubMainFrm(WebEntryPoint w, IMDBObj i)
  {
    // Sono una form multipla, duplico IMDB
    IMDB = new IMDBObj();
    IMDB.set_DBSize(w.IwImdb.IMDB.DBSize());
    ImdbInit(IMDB);
    IMDB.SetMaster(w.IwImdb.IMDB);
    super.SetSubMainFrm(w, i);
  }


  // **********************************************
  // Costruttore per form multiple
  // **********************************************
  public InfoDispProvv()
  {
    super();
    //
  }

  // **********************************************
  // Form Loaded
  // **********************************************
  public void Init(WebEntryPoint w, boolean flMulti, boolean flSubForm)
  {
    StringBuffer SQL;
    int i;
    ATreeItem Item;

    MainFrm=(MyWebEntryPoint)w;
    super.Init(w, flMulti, flSubForm);
    //
    FormIdx = MyGlb.FRM_INFODISPPROV;
    //
    if (flMulti)
      MainFrm.AddMultipleForm(this, flSubForm);
    //
    boolean oldIQ = MainFrm.InitializingQueries;
    MainFrm.InitializingQueries = true;
    //
    RTCGuid = "71D65005-204E-45F4-A0AC-DA7EFC2E1B1B";
    ResModeW = 3;
    ResModeH = 1;
    iBorderType = 2;
    iVisualFlags = -4057;
    DesignWidth = 740;
    DesignHeight = 166;
    set_Caption(new IDVariant("Info Disponibilità Provvisoria"));
    //
    Frames = new AFrame[2];
    Frames[1] = new AFrame(1);
    Frames[1].Parent = this;
    Frames[1].Width = 740;
    Frames[1].Height = 140;
    Frames[1].FrHidden = true;
    Frames[1].Caption = "Info Disponibilita Provvisoria";
    Frames[1].Parent = this;
    Frames[1].FixedHeight = 140;
    PAN_INFODISPPROV = new IDPanel(w, this, 1, "PAN_INFODISPPROV");
    Frames[1].Content = PAN_INFODISPPROV;
    PAN_INFODISPPROV.ShowRowSelector = false;
    PAN_INFODISPPROV.ShowToolbar = false;
    PAN_INFODISPPROV.ShowStatusbar = false;
    PAN_INFODISPPROV.iLocked = false;
    PAN_INFODISPPROV.set_VisualFlag(Glb.PANVISPROP_HILITEROW,true);
    PAN_INFODISPPROV.VS = MainFrm.VisualStyleList;
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_RECT, 0, 0, 0, 0, 740-MyGlb.PAN_OFFS_X, 140-MyGlb.PAN_OFFS_Y, 0, 0);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_PANEL, 0, "C917537D-4163-4DBF-9CA9-CE81CB4909BF");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_PANEL, 0, 0, 0, 0, 1036, 120, MyGlb.RESMODE_NONE, MyGlb.RESMODE_STRETCH);
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_PANEL, 0, MyGlb.VIS_DEFAPANESTYL);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_PANEL, 0, 0, 0);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_PANEL, 0, MainFrm.GlbPanelFlags | MyGlb.PAN_SCROLLREC | MyGlb.PAN_HASFORM | MyGlb.PAN_STARTFORM | MyGlb.OBJ_VISIBLE | MyGlb.OBJ_ENABLED, -1);
    PAN_INFODISPPROV.InitStatus = 2;
    PAN_INFODISPPROV_Init();
    PAN_INFODISPPROV_InitFields();
    PAN_INFODISPPROV_InitQueries();
    HelpFile = "";
    MainFrm.InitializingQueries = false;
    //
    // Modifico alcune impostazioni per smartphone, potranno
    // essere ulteriormente modificate nell'evento di Load
    if (MainFrm.IsSmartPhone())
    {
      DockType = 0;
      Docked = false;
      ResModeW = Glb.FRESMODE_STRETCH;
      ResModeH = Glb.FRESMODE_STRETCH;
    }
    //
    for (i=1; i<Frames.length; i++)
    {
      if (Frames[i].Content instanceof IDPanel)
      {
        Frames[i].Content.MainFrm = w;
        Frames[i].Content.Parent = this;
        ((IDPanel)Frames[i].Content).CalcLayout();
        ((IDPanel)Frames[i].Content).SetDOIMDB(IMDB);
      }
      if (Frames[i].Content instanceof OBook)
        Frames[i].Content.MainFrm = w;
      //
      if (Frames[i].Content != null)
        Frames[i].Content.Collapsable = w.ParamsObj().UseCollapsableFrames;
      //
      if (Frames[i].Content != null && Frames[i].HasCaptionToolbar==-1)
        Frames[i].HasCaptionToolbar = MainFrm.CmdObj.HasCaptionToolbar(FormIdx, Frames[i].Index, Frames[i].Content.Code);
    }
    //
    // Init sub-frames
    for (i = 1; i < Frames.length; i++)
    {
      if (Frames[i].Content instanceof IDPanel)
        for (int j = 0; j < ((IDPanel)Frames[i].Content).UFields(); j++)
          ((IDPanel)Frames[i].Content).bFields(j).UpdateSubFrame();
    }
    //
    for (i=1; i<Frames.length; i++)
    {
      if (Frames[i].Content instanceof OTabView)
        ((OTabView)Frames[i].Content).SelectTab(1, true);
    }
    OrgWidth = Frames[1].Width + GetPadding(false);
    OrgHeight = Frames[1].Height + GetPadding(true);
    //
    // Resetto il fuoco perchè le tabbed view lo possono modificare
    FocusPriority=0;
    ActiveElement="";
    //
    MainFrm.RolObj.ApplyRoles(FormIdx, this);
    //
    MainFrm.TimerObj.ActivateTimers(FormIdx, true);    
    IntFormLoad();
    //
    // Solo le form non modali devono essere ridimensionate
    if (!flSubForm && (!MainFrm.ParamsObj().TruePopup || OpenAs == Glb.OPEN_MDI))
      Resize(w.ScreenW(), w.ScreenH());
    //
    JustLoaded = true;
    UpdateControls();
    MainFrm.InitializingQueries = oldIQ;
  }


  // **********************************************
  // Command Activation Handler
  // **********************************************
  public void CmdClickCB(int CmdIdx)
  {
    fine:
    {
    }
  }
  
  
  // **********************************************
  // Timer Activation Handler
  // **********************************************
  public void TimerTickCB(int TimerIdx)
  {
    fine:
    {
    }
  }
  
  
  // **********************************************
  // Update Controls against IMDB variations
  // **********************************************
  public void UpdateControls()
  {
    try
    {    
      if (IMDB.TblModified(IMDBDef7.TBL_PARAMETRI501, MyGlb.GlbRefModIdx) || JustLoaded)
      {
        INFODISPPROV_PARAMETRI505();
      }
      PAN_INFODISPPROV.UpdatePanel(MainFrm);
      //
    }
    catch(Exception e)
    {
      e.printStackTrace(System.out);
    }
    JustLoaded = false;
    DOSetCaption();
    super.UpdateControls();
  }
  
  
  // **********************************************
  // One of my modal form has been closed
  // **********************************************
  public void EndModal(int CallerIdx, boolean flRis)
  {
    IDVariant Cancel=new IDVariant();
    IntEndModal(new IDVariant(CallerIdx), new IDVariant(flRis), Cancel);
    if (Cancel.isTrue())
    {
      if (MainFrm != null) MainFrm.DTTObj.AddMsg(DTTEngine.DTTMSG_INFO, RTCGuid, 26, "Form.EndModal", "Form " + Caption() + " canceled further processing after EndModal event");
      return;
    }
    //
  }
  

  // **********************************************
  // Enumerate books
  // **********************************************
  public CIDREObj SearchBook(String Code)
  {
    //
    return null;
  }

  // **************************************************
  // Torna TRUE se l'oggetto passato è una mia istanza
  // **************************************************
  public static boolean IsMyInstance(Object obj)
  {
    return (obj instanceof InfoDispProvv);
  }

  // **********************************************
  // Restituisce il nome della classe
  // **********************************************
  public static String GetClassName(boolean FullName)
  {
    return (FullName ? InfoDispProvv.class.getName() : (Glb.ClassWithPackage(InfoDispProvv.class) ? InfoDispProvv.class.getName().substring(InfoDispProvv.class.getPackage().getName().length() + 1) : InfoDispProvv.class.getName()));
  }
  

  // **********************************************
  // Procedure Definition
  // **********************************************  
  // **********************************************************************
  // Load
  // Evento notificato alla videata al momento del caricamento
  // in memoria.
  // **********************************************************************
  private void IntFormLoad ()
  {
    StringBuffer SQL = new StringBuffer();
    int TransCount   = 0;
    int ReturnStatus = 0;
    IDCachedRowSet QV;

    try
    {
      TransCount = 0;
      MainFrm.IntFormLoad(this);
      // 
      // Load Body
      // Corpo Procedura
      // 
      SQL = new StringBuffer();
      SQL.append("select ");
      SQL.append("  NVL(GET_IMPORTI_SCHEDA_INFO(" + IDL.CSql(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARAMESERCIZ, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRENES, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRCAPI, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRARTI, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + ",'VAR_PROV_TOT'," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORTIPRAM, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORMISTIT, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODSTR, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI1, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI2, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI3, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI4, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORTIPUO, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORUOGES, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRRESP, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCEDICO, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(MainFrm.PROGRESESSIO, IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRFINA, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORROPER, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRESPL, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI5, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "), 0) as NVCDGISIPEN1, ");
      SQL.append("  NVL(GET_IMPORTI_SCHEDA_INFO(" + IDL.CSql(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARAMESERCIZ, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRENES, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRCAPI, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRARTI, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + ",'VAR_PROV_ESI'," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORTIPRAM, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORMISTIT, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODSTR, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI1, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI2, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI3, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI4, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORTIPUO, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORUOGES, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRRESP, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCEDICO, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(MainFrm.PROGRESESSIO, IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRFINA, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORROPER, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRESPL, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI5, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "), 0) as NVCDGISIPENC, ");
      SQL.append("  NVL(GET_IMPORTI_SCHEDA_INFO(" + IDL.CSql(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARAMESERCIZ, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRENES, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRCAPI, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRARTI, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + ",'VAR_PROV_STN'," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORTIPRAM, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORMISTIT, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODSTR, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI1, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI2, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI3, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI4, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORTIPUO, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORUOGES, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRRESP, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCEDICO, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(MainFrm.PROGRESESSIO, IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRFINA, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORROPER, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRESPL, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI5, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "), 0) as NVGISIPENCE1, ");
      SQL.append("  NVL(GET_IMPORTI_SCHEDA_INFO(" + IDL.CSql(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARAMESERCIZ, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRENES, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRCAPI, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRARTI, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + ",'VAR_PROV_CA'," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORTIPRAM, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORMISTIT, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODSTR, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI1, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI2, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI3, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI4, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORTIPUO, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORUOGES, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRRESP, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCEDICO, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(MainFrm.PROGRESESSIO, IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRFINA, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORROPER, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRESPL, 0), IDL.FMT_CHAR, MainFrm.Cf4armDBObject.DBO()) + "," + IDL.CSql(IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODCORCODLI5, 0), IDL.FMT_NUM, MainFrm.Cf4armDBObject.DBO()) + "), 0) as NVGISIPENCES ");
      SQL.append("from ");
      SQL.append("  DUAL A ");
      QV = MainFrm.Cf4armDBObject.DBO().OpenRS(SQL);
      if (!QV.EOF()) QV.MoveNext();
      if (!QV.EOF())
      {
        IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROTOT, 0, QV.Get("NVCDGISIPEN1", IDVariant.DECIMAL));
        IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROESI, 0, QV.Get("NVCDGISIPENC", IDVariant.DECIMAL));
        IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROSTN, 0, QV.Get("NVGISIPENCE1", IDVariant.DECIMAL));
        IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROCAS, 0, QV.Get("NVGISIPENCES", IDVariant.DECIMAL));
      }
      QV.Close();
      IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROPUR, 0, IDL.Sub(IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROTOT, 0),(new IDVariant(0))), (IDL.Add(IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROESI, 0),(new IDVariant(0))), IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROSTN, 0),(new IDVariant(0)))))));
      IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATTOPR, 0, IDL.Add(IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARAMSTANATT, 0),(new IDVariant(0))), IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROTOT, 0),(new IDVariant(0)))));
      IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATESPR, 0, IDL.Add(IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATTESI, 0),(new IDVariant(0))), IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROESI, 0),(new IDVariant(0)))));
      IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATSTPR, 0, IDL.Add(IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATTSTN, 0),(new IDVariant(0))), IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROSTN, 0),(new IDVariant(0)))));
      IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATCAPR, 0, IDL.Add(IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATTCAS, 0),(new IDVariant(0))), IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROCAS, 0),(new IDVariant(0)))));
      IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATPUPR, 0, IDL.Sub(IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATTOPR, 0),(new IDVariant(0))), (IDL.Add(IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATESPR, 0),(new IDVariant(0))), IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATSTPR, 0),(new IDVariant(0)))))));
      IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISTOTPRO, 0, IDL.Add(IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARAMDISPONI, 0),(new IDVariant(0))), IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROTOT, 0),(new IDVariant(0)))));
      IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISESIPRO, 0, IDL.Add(IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARAMDISPESI, 0),(new IDVariant(0))), IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROESI, 0),(new IDVariant(0)))));
      IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISSTNPRO, 0, IDL.Add(IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARAMDISPSTN, 0),(new IDVariant(0))), IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROSTN, 0),(new IDVariant(0)))));
      IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISCASPRO, 0, IDL.Add(IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARADISPCASS, 0),(new IDVariant(0))), IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROCAS, 0),(new IDVariant(0)))));
      IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISPURPRO, 0, IDL.Sub(IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISTOTPRO, 0),(new IDVariant(0))), (IDL.Add(IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISESIPRO, 0),(new IDVariant(0))), IDL.NullValue(IMDB.Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISSTNPRO, 0),(new IDVariant(0)))))));
      if (IMDB.Value(IMDBDef7.TBL_VALONODOCORR, IMDBDef7.FLD_VALONODOCORR_NODOCORRENES, 0).equals((new IDVariant("E")), true))
      {
        PAN_INFODISPPROV.SetFlags (Glb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDASTA, ((new IDVariant(0)).booleanValue())? Glb.OBJ_VISIBLE : 0, Glb.OBJ_VISIBLE); 
        PAN_INFODISPPROV.SetFlags (Glb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, ((new IDVariant(0)).booleanValue())? Glb.OBJ_VISIBLE : 0, Glb.OBJ_VISIBLE); 
        PAN_INFODISPPROV.SetFlags (Glb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, ((new IDVariant(0)).booleanValue())? Glb.OBJ_VISIBLE : 0, Glb.OBJ_VISIBLE); 
        PAN_INFODISPPROV.SetFlags (Glb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, ((new IDVariant(0)).booleanValue())? Glb.OBJ_VISIBLE : 0, Glb.OBJ_VISIBLE); 
      }
      else
      {
        PAN_INFODISPPROV.SetFlags (Glb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDASTA, ((new IDVariant(-1)).booleanValue())? Glb.OBJ_VISIBLE : 0, Glb.OBJ_VISIBLE); 
        PAN_INFODISPPROV.SetFlags (Glb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, ((new IDVariant(-1)).booleanValue())? Glb.OBJ_VISIBLE : 0, Glb.OBJ_VISIBLE); 
        PAN_INFODISPPROV.SetFlags (Glb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, ((new IDVariant(-1)).booleanValue())? Glb.OBJ_VISIBLE : 0, Glb.OBJ_VISIBLE); 
        PAN_INFODISPPROV.SetFlags (Glb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, ((new IDVariant(-1)).booleanValue())? Glb.OBJ_VISIBLE : 0, Glb.OBJ_VISIBLE); 
      }
    }
    catch (Exception _e)
    {
      MainFrm.ErrObj.ProcError ("InfoDispProvv", "Load", _e);
    }
  }

  // **********************************************************************
  // Unload
  // Evento notificato dal form prima della chiusura dello
  // stesso
  // Cancel - Input/Output
  // Confirm - Input
  // **********************************************************************
  public void IntFormUnload (IDVariant Cancel, IDVariant Confirm)
  {
    StringBuffer SQL = new StringBuffer();
    int TransCount   = 0;
    int ReturnStatus = 0;
    IDCachedRowSet QV;

    try
    {
      TransCount = 0;
      // 
      // Unload Body
      // Corpo Procedura
      // 
      UNLOAD_PARAMEDELETE();
    }
    catch (Exception _e)
    {
      MainFrm.ErrObj.ProcError ("InfoDispProvv", "Unload", _e);
    }
  }

  // **********************************************************************
  // Parametri: Delete
  // Perchè stai eliminando questi dati?
  // **********************************************************************
  private void UNLOAD_PARAMEDELETE() throws SQLException
  {
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARAMESERCIZ, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARAMSTANATT, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATTESI, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATTSTN, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATTCAS, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARAMDISPONI, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARAMDISPESI, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARAMDISPSTN, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARADISPCASS, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROTOT, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROPUR, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROESI, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROSTN, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROCAS, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATTOPR, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATPUPR, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATESPR, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATSTPR, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATCAPR, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISTOTPRO, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISPURPRO, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISESIPRO, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISSTNPRO, 0, new IDVariant());
    IMDB.set_Value(IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISCASPRO, 0, new IDVariant());
  }

  // **********************************************************************
  // Activate
  // Evento notificato alla videata quando essa viene attivata
  // cioè quando viene portata in primo piano
  // **********************************************************************
  public void Form_Activate()
  {
    StringBuffer SQL = new StringBuffer();
    int TransCount   = 0;
    int ReturnStatus = 0;
    IDCachedRowSet QV;

    try
    {
      TransCount = 0;
      MainFrm.Form_Activate(this);
      // 
      // Activate Body
      // Corpo Procedura
      // 
      if ((MainFrm.GetForm(MyGlb.FRM_SCHEDINFOBIL, 0, false)!=null))
      {
        MainFrm.GetForm(MyGlb.FRM_SCHEDINFOBIL,0).set_WindowState((new IDVariant(0)).intValue());
      }
    }
    catch (Exception _e)
    {
      MainFrm.ErrObj.ProcError ("InfoDispProvv", "Activate", _e);
    }
  }

  // **********************************************************************
  // Parametri
  // Recupera i record da mostrare nel pannello
  // **********************************************************************
  private void INFODISPPROV_PARAMETRI505() throws SQLException
  {
    IDVariant[] AggrBuff;
    int[] AggrRowCount;
    int AggrCount=0;
    boolean AggrNewGroup = false;

    IMDB.TblTruncate(IMDBDef17.PQRY_PARAMETRI505_RS);
    IMDB.TblMoveFirst(IMDBDef7.TBL_PARAMETRI501, 0);
    Loop1: while (!IMDB.Eof(IMDBDef7.TBL_PARAMETRI501, 0))
    {
      IMDB.TblAddNew(IMDBDef17.PQRY_PARAMETRI505_RS, 0);
      IMDB.TblLinkRow(IMDBDef17.PQRY_PARAMETRI505_RS, 0, IMDBDef7.TBL_PARAMETRI501, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 0, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROTOT, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 1, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROPUR, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 2, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROESI, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 3, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROSTN, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 4, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARVARPROCAS, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 5, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATTOPR, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 6, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATPUPR, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 7, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATESPR, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 8, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATSTPR, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 9, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARSTAATCAPR, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 10, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISTOTPRO, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 11, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISPURPRO, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 12, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISESIPRO, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 13, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISSTNPRO, 0);
      IMDB.TblLinkField(IMDBDef17.PQRY_PARAMETRI505_RS, 14, 0, IMDBDef7.TBL_PARAMETRI501, IMDBDef7.FLD_PARAMETRI501_PARDISCASPRO, 0);
      IMDB.TblMoveNext(IMDBDef7.TBL_PARAMETRI501, 0);
      if (IMDB.Eof(IMDBDef7.TBL_PARAMETRI501, 0))
      {
        IMDB.TblMoveFirst(IMDBDef7.TBL_PARAMETRI501, 0);
      }
      else
      {
        continue Loop1;
      }
      break;
    }
    IMDB.TblMoveFirst(IMDBDef17.PQRY_PARAMETRI505_RS, 0);
  }

  
  
  // **********************************************
  // Event Stubs
  // **********************************************  
  // **********************************************************************
  // Deactivate
  // Evento notificato alla videata quando essa viene messa
  // in secondo piano
  // **********************************************************************
  public void Form_Deactivate(IDVariant Cancel)
  {
    // Stub
  }

  // **********************************************************************
  // End Modal
  // Evento notificato dall'oggetto form in applicazioni
  // Web quando viene chiusa una finestra modale
  // **********************************************************************
  private void IntEndModal(IDVariant LookupForm,IDVariant Result,IDVariant Cancel)
  {
    // Stub
  }

  // **********************************************************************
  // On Change Document
  // Evento notificato al form quando viene cambiato il
  // documento collegato
  // **********************************************************************
  public void OnChangeDocument(com.progamma.doc.IDDocument OldDocument)
  {
    // Stub
  }

  // **********************************************************************
  // On Send Message
  // Evento notificato quando una videata invia un messaggio
  // tramite la procedura SendMessage
  // **********************************************************************
  public void OnSendMessage(IDVariant Message, WebForm Sender, com.progamma.doc.IDDocument Doc, IDVariant Par1, IDVariant Par2, IDVariant Par3, IDVariant Par4)
  {
    // Stub
  }

  
  
  // **********************************************
  // Frame Events
  // **********************************************
  // **********************************************************************
  // On Database Error
  // Evento notificato dal pannello al verificarsi di un
  // errore di database durante un'operazione di salvataggio
  // dei dati.
  // **********************************************************************
  private void PAN_INFODISPPROV_OnDBError(IDVariant Cancel, IDVariant Skip, IDVariant ErrorNumber, IDVariant ErrorMessage, IDVariant NativeErrorNumber, IDVariant PanelOperation, com.progamma.doc.IDDocument Doc)
  {
      MainFrm.OnDBError(PAN_INFODISPPROV, Cancel, Skip, ErrorNumber, ErrorMessage, NativeErrorNumber, PanelOperation, Doc);
    // Stub
  }

  // **********************************************************************
  // On Validate Row
  // Evento notificato dal pannello quando un utente modifica
  // i dati presenti nel pannello
  // **********************************************************************
  private void PAN_INFODISPPROV_IntValidateRow (IDVariant Cancel)
  {
      MainFrm.IntValidateRow(PAN_INFODISPPROV, Cancel);
    // Stub
  }

  // **********************************************************************
  // On Dynamic Properties
  // Consente l'aggiustamento delle proprietà visuali delle
  // singole celle del pannello.
  // **********************************************************************
  private void PAN_INFODISPPROV_DynamicProperties ()
  {
      MainFrm.DynamicProperties(PAN_INFODISPPROV);
    // Stub
  }

  private void PAN_INFODISPPROV_CellActivated(IDVariant ColIndex, IDVariant Cancel)
  {
    int i = 0;
  }

  private void PAN_INFODISPPROV_ValidateCell(IDVariant ColIndex, IDVariant CellModified, IDVariant Cancel, IDVariant FldWasModified, IDVariant RowWasModified, IDVariant IsInsert)
  {
    try
    {
    }
    catch(Exception e) {}
  }

  private void PAN_INFODISPPROV_ValidateRow(IDVariant Cancel)
  {
    try
    {
      if (Cancel.isFalse())
      {
        PAN_INFODISPPROV_IntValidateRow(Cancel);
      }
    } catch ( Exception e) { }
  }

  
  
  // **********************************************
  // Panel (long) initialization
  // **********************************************
  private void PAN_INFODISPPROV_Init()
  {

    PAN_INFODISPPROV.SetSize(MyGlb.OBJ_PAGE, 0);
    PAN_INFODISPPROV.SetSize(MyGlb.OBJ_GROUP, 0);
    PAN_INFODISPPROV.SetSize(MyGlb.OBJ_FIELD, 20);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVTOT, "61B439E1-E64A-4CF2-B8C5-CF2BFAAD184C");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVTOT, "Variazioni Provvisorie");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVTOT, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVTOT, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVTOT, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVPURO, "DBAAEBDF-2C4F-4D0C-BAAD-1E7D7DDE30FD");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVPURO, "Residuo");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVPURO, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVPURO, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVPURO, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_NOHDRLIST | MyGlb.FLD_NOHDRFORM | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVESI, "C765B5F2-02CC-4207-AD2C-0881F560813A");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVESI, "Var Prov Esi");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVESI, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVESI, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVESI, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_LISTLIST | MyGlb.FLD_INLIST | MyGlb.FLD_NOHDRFORM | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, "335C86C5-19EC-4ADC-8E5E-E7F2B6614FFF");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, "Var Prov Stn");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_LISTLIST | MyGlb.FLD_INLIST | MyGlb.FLD_NOHDRFORM | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVCASSA, "EF4B535D-08C4-4B15-B006-D6C05D880D38");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVCASSA, "Variazioni Cassa");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVCASSA, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVCASSA, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVCASSA, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_NOHDRFORM | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTTOT, "5C8D011E-0B8B-4679-94A9-77403D2CE560");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTTOT, "Stanz. Att. Provvisorio");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTTOT, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTTOT, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTTOT, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTPURO, "9BE8ED1F-80AD-473B-B1C0-D6EB993C6783");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTPURO, "su Comp. Pura");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTPURO, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTPURO, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTPURO, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_NOHDRLIST | MyGlb.FLD_NOHDRFORM | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTESI, "5A1A1EC1-9D95-4962-A6A6-8CDD1A227B55");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTESI, "Stanz Att Esi");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTESI, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTESI, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTESI, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_LISTLIST | MyGlb.FLD_INLIST | MyGlb.FLD_NOHDRFORM | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, "BBF4B4A4-A3D8-489F-A44F-4F1D8CEB81A8");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, "Stanz Att Stn");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_LISTLIST | MyGlb.FLD_INLIST | MyGlb.FLD_NOHDRFORM | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTCASS, "02415616-7F55-4ED2-84A1-9A3DA421C868");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTCASS, "Stanz. Att. Cassa");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTCASS, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTCASS, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTCASS, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_NOHDRFORM | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPTOT, "5DDD7AC5-0D3F-48CA-BFF9-D0FCDD30F4B8");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPTOT, "Disponibilità Provvisoria");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPTOT, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPTOT, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPTOT, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_SUREISCRIZIO, "C6A7F824-EF22-4C09-AEE0-A85415DCBC03");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_SUREISCRIZIO, "su Reiscrizioni");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_SUREISCRIZIO, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_SUREISCRIZIO, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_SUREISCRIZIO, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_LISTLIST | MyGlb.FLD_INLIST | MyGlb.FLD_NOHDRLIST | MyGlb.FLD_NOHDRFORM | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPESI, "E52403D2-7D63-48DB-84DC-BF07540836AB");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPESI, "Disp Esi");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPESI, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPESI, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPESI, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_LISTLIST | MyGlb.FLD_INLIST | MyGlb.FLD_NOHDRFORM | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, "982B148B-FF14-42AD-8CA8-BD8B8ED1CE3F");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, "Disp Stn");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_LISTLIST | MyGlb.FLD_INLIST | MyGlb.FLD_NOHDRFORM | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPCASSA, "7AC0FC1C-20F9-4BC1-A3CA-550D7D08CFE5");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPCASSA, "Disponibilità Cassa");
    PAN_INFODISPPROV.set_ToolTip(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPCASSA, "");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPCASSA, MyGlb.VIS_NORFIECF4IMP);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPCASSA, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_NOHDRFORM | MyGlb.FLD_INFORM | MyGlb.FLD_ISOPT, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETTCOMP, "5508B4E0-EE8E-4DBB-ABEA-18191465C3FF");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETTCOMP, "Puro");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETTCOMP, MyGlb.VIS_VUOTOGRASSET);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETTCOMP, 0 | MyGlb.OBJ_ENABLED | MyGlb.OBJ_VISIBLE | MyGlb.FLD_INFORM, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETOTALE, "F07C7525-74EC-426E-A0FB-F8C458B7D960");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETOTALE, "Totale");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETOTALE, MyGlb.VIS_VUOTOGRASSET);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETOTALE, 0 | MyGlb.OBJ_VISIBLE | MyGlb.FLD_INFORM, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETCASSA, "31C0E666-102E-48EA-B1E7-3492C1522E0E");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETCASSA, "Cassa");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETCASSA, MyGlb.VIS_VUOTOGRASSET);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETCASSA, 0 | MyGlb.OBJ_ENABLED | MyGlb.OBJ_VISIBLE | MyGlb.FLD_INFORM, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDAESI, "5B74403B-933D-4F6A-BBA8-AFF10242F18A");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDAESI, "Reiscrizioni da Esigibilità");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDAESI, MyGlb.VIS_VUOTOGRASSET);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDAESI, 0 | MyGlb.OBJ_ENABLED | MyGlb.OBJ_VISIBLE | MyGlb.FLD_INFORM, -1);
    PAN_INFODISPPROV.SetRTCGuid(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDASTA, "AA6E2595-AC64-4957-922E-78C1DB1C8784");
    PAN_INFODISPPROV.set_Header(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDASTA, "Reiscrizioni da Stanziamento");
    PAN_INFODISPPROV.set_VisualStyle(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDASTA, MyGlb.VIS_VUOTOGRASSET);
    PAN_INFODISPPROV.SetFlags(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDASTA, 0 | MyGlb.OBJ_ENABLED | MyGlb.OBJ_VISIBLE | MyGlb.FLD_INFORM, -1);
  }

  private void PAN_INFODISPPROV_InitFields()
  {

    StringBuffer SQL = new StringBuffer();
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVTOT, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVTOT, MyGlb.PANEL_LIST, 60);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVTOT, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVTOT, MyGlb.PANEL_LIST, "Variazioni Provvisorie");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVTOT, MyGlb.PANEL_FORM, 28, 44, 244, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVTOT, MyGlb.PANEL_FORM, 136);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVTOT, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVTOT, MyGlb.PANEL_FORM, "Variazioni Provvisorie");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_VARPROVTOT, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_VARPROVTOT, PPQRY_PARAMETRI505, "A.PARVARPROTOT", "RECVARPROTOT", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVPURO, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVPURO, MyGlb.PANEL_LIST, 88);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVPURO, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVPURO, MyGlb.PANEL_LIST, "Residuo");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVPURO, MyGlb.PANEL_FORM, 280, 44, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVPURO, MyGlb.PANEL_FORM, 120);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVPURO, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVPURO, MyGlb.PANEL_FORM, "Residuo");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_VARPROVPURO, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_VARPROVPURO, PPQRY_PARAMETRI505, "A.PARVARPROPUR", "RECVARPROPUR", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVESI, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVESI, MyGlb.PANEL_LIST, 56);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVESI, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVESI, MyGlb.PANEL_LIST, "Var Prov Esi");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVESI, MyGlb.PANEL_FORM, 392, 44, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVESI, MyGlb.PANEL_FORM, 56);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVESI, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVESI, MyGlb.PANEL_FORM, "V. Pr. Es.");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_VARPROVESI, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_VARPROVESI, PPQRY_PARAMETRI505, "A.PARVARPROESI", "RECVARPROESI", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, MyGlb.PANEL_LIST, 52);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, MyGlb.PANEL_LIST, "Var Prov Stn");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, MyGlb.PANEL_FORM, 504, 44, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, MyGlb.PANEL_FORM, 52);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVSTN, MyGlb.PANEL_FORM, "V. Pr. St.");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_VARPROVSTN, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_VARPROVSTN, PPQRY_PARAMETRI505, "A.PARVARPROSTN", "RECVARPROSTN", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVCASSA, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVCASSA, MyGlb.PANEL_LIST, 60);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVCASSA, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVCASSA, MyGlb.PANEL_LIST, "Variazioni Cassa");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVCASSA, MyGlb.PANEL_FORM, 616, 44, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVCASSA, MyGlb.PANEL_FORM, 120);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVCASSA, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_VARPROVCASSA, MyGlb.PANEL_FORM, "Variazioni Cassa");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_VARPROVCASSA, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_VARPROVCASSA, PPQRY_PARAMETRI505, "A.PARVARPROCAS", "RECVARPROCAS", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTTOT, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTTOT, MyGlb.PANEL_LIST, 80);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTTOT, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTTOT, MyGlb.PANEL_LIST, "Stanz. Att. Provvisorio");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTTOT, MyGlb.PANEL_FORM, 28, 68, 244, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTTOT, MyGlb.PANEL_FORM, 136);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTTOT, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTTOT, MyGlb.PANEL_FORM, "Stanz. Att. Provvisorio");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_STANZATTTOT, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_STANZATTTOT, PPQRY_PARAMETRI505, "A.PARSTAATTOPR", "RECSTAATTOPR", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTPURO, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTPURO, MyGlb.PANEL_LIST, 80);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTPURO, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTPURO, MyGlb.PANEL_LIST, "su Comp. Pura");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTPURO, MyGlb.PANEL_FORM, 280, 68, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTPURO, MyGlb.PANEL_FORM, 120);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTPURO, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTPURO, MyGlb.PANEL_FORM, "su Comp. Pura");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_STANZATTPURO, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_STANZATTPURO, PPQRY_PARAMETRI505, "A.PARSTAATPUPR", "RECSTAATPUPR", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTESI, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTESI, MyGlb.PANEL_LIST, 76);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTESI, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTESI, MyGlb.PANEL_LIST, "Stanz Att Esi");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTESI, MyGlb.PANEL_FORM, 392, 68, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTESI, MyGlb.PANEL_FORM, 76);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTESI, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTESI, MyGlb.PANEL_FORM, "St. Att Esi");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_STANZATTESI, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_STANZATTESI, PPQRY_PARAMETRI505, "A.PARSTAATESPR", "RECSTAATESPR", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, MyGlb.PANEL_LIST, 72);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, MyGlb.PANEL_LIST, "Stanz Att Stn");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, MyGlb.PANEL_FORM, 504, 68, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, MyGlb.PANEL_FORM, 72);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTSTN, MyGlb.PANEL_FORM, "St. Att Stn");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_STANZATTSTN, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_STANZATTSTN, PPQRY_PARAMETRI505, "A.PARSTAATSTPR", "RECSTAATSTPR", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTCASS, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTCASS, MyGlb.PANEL_LIST, 80);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTCASS, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTCASS, MyGlb.PANEL_LIST, "Stanz. Att. Cassa");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTCASS, MyGlb.PANEL_FORM, 616, 68, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTCASS, MyGlb.PANEL_FORM, 120);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTCASS, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_STANZATTCASS, MyGlb.PANEL_FORM, "Stanz. Att. Cassa");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_STANZATTCASS, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_STANZATTCASS, PPQRY_PARAMETRI505, "A.PARSTAATCAPR", "RECSTAATCAPR", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPTOT, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPTOT, MyGlb.PANEL_LIST, 64);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPTOT, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPTOT, MyGlb.PANEL_LIST, "Disponibilità Provvisoria");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPTOT, MyGlb.PANEL_FORM, 16, 92, 256, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPTOT, MyGlb.PANEL_FORM, 148);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPTOT, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPTOT, MyGlb.PANEL_FORM, "Disponibilità Provvisoria");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_DISPTOT, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_DISPTOT, PPQRY_PARAMETRI505, "A.PARDISTOTPRO", "RECDISTOTPRO", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_SUREISCRIZIO, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_SUREISCRIZIO, MyGlb.PANEL_LIST, 72);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_SUREISCRIZIO, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_SUREISCRIZIO, MyGlb.PANEL_LIST, "su Reiscrizioni");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_SUREISCRIZIO, MyGlb.PANEL_FORM, 280, 92, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_SUREISCRIZIO, MyGlb.PANEL_FORM, 120);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_SUREISCRIZIO, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_SUREISCRIZIO, MyGlb.PANEL_FORM, "su Reiscrizioni");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_SUREISCRIZIO, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_SUREISCRIZIO, PPQRY_PARAMETRI505, "A.PARDISPURPRO", "RECDISPURPRO", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPESI, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPESI, MyGlb.PANEL_LIST, 60);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPESI, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPESI, MyGlb.PANEL_LIST, "Disp Esi");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPESI, MyGlb.PANEL_FORM, 392, 92, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPESI, MyGlb.PANEL_FORM, 60);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPESI, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPESI, MyGlb.PANEL_FORM, "Disp Esi");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_DISPESI, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_DISPESI, PPQRY_PARAMETRI505, "A.PARDISESIPRO", "RECDISESIPRO", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, MyGlb.PANEL_LIST, 56);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, MyGlb.PANEL_LIST, "Disp Stn");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, MyGlb.PANEL_FORM, 504, 92, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, MyGlb.PANEL_FORM, 56);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPSTN, MyGlb.PANEL_FORM, "Disp Stn");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_DISPSTN, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_DISPSTN, PPQRY_PARAMETRI505, "A.PARDISSTNPRO", "RECDISSTNPRO", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPCASSA, MyGlb.PANEL_LIST, 0, 0, 148, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPCASSA, MyGlb.PANEL_LIST, 64);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPCASSA, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPCASSA, MyGlb.PANEL_LIST, "Disponibilità Cassa");
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPCASSA, MyGlb.PANEL_FORM, 616, 92, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPCASSA, MyGlb.PANEL_FORM, 120);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPCASSA, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetAbbrHeader(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_DISPCASSA, MyGlb.PANEL_FORM, "Disponibilità Cassa");
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_DISPCASSA, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_DISPCASSA, PPQRY_PARAMETRI505, "A.PARDISCASPRO", "RECDISCASPRO", 3, 14, 2, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETTCOMP, MyGlb.PANEL_LIST, 144, 8, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETTCOMP, MyGlb.PANEL_LIST, 0);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETTCOMP, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETTCOMP, MyGlb.PANEL_FORM, 280, 16, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETTCOMP, MyGlb.PANEL_FORM, 0);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETTCOMP, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_ETICHETTCOMP, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_ETICHETTCOMP, -1, "", "ETICHETTCOMP", 0, 0, 0, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETOTALE, MyGlb.PANEL_LIST, 300, 12, 68, 16, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETOTALE, MyGlb.PANEL_LIST, 0);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETOTALE, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETOTALE, MyGlb.PANEL_FORM, 168, 16, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETOTALE, MyGlb.PANEL_FORM, 0);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETOTALE, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_ETICHETOTALE, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_ETICHETOTALE, -1, "", "ETICHETOTALE", 0, 0, 0, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETCASSA, MyGlb.PANEL_LIST, 448, 12, 64, 16, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETCASSA, MyGlb.PANEL_LIST, 0);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETCASSA, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETCASSA, MyGlb.PANEL_FORM, 616, 18, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETCASSA, MyGlb.PANEL_FORM, 0);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICHETCASSA, MyGlb.PANEL_FORM, 1);
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_ETICHETCASSA, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_ETICHETCASSA, -1, "", "ETICHETCASSA", 0, 0, 0, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDAESI, MyGlb.PANEL_LIST, 152, 16, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDAESI, MyGlb.PANEL_LIST, 0);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDAESI, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDAESI, MyGlb.PANEL_FORM, 392, 8, 104, 32, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDAESI, MyGlb.PANEL_FORM, 0);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDAESI, MyGlb.PANEL_FORM, 2);
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_ETICREIDAESI, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_ETICREIDAESI, -1, "", "ETICREIDAESI", 0, 0, 0, -13997);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDASTA, MyGlb.PANEL_LIST, 160, 24, 104, 20, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDASTA, MyGlb.PANEL_LIST, 0);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDASTA, MyGlb.PANEL_LIST, 1);
    PAN_INFODISPPROV.SetRect(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDASTA, MyGlb.PANEL_FORM, 504, 8, 104, 32, MyGlb.RESMODE_NONE, MyGlb.RESMODE_NONE);
    PAN_INFODISPPROV.SetHeaderSize(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDASTA, MyGlb.PANEL_FORM, 0);
    PAN_INFODISPPROV.SetNumRow(MyGlb.OBJ_FIELD, PFL_INFODISPPROV_ETICREIDASTA, MyGlb.PANEL_FORM, 2);
    PAN_INFODISPPROV.SetFieldPage(PFL_INFODISPPROV_ETICREIDASTA, -1, -1);
    PAN_INFODISPPROV.SetFieldPanel(PFL_INFODISPPROV_ETICREIDASTA, -1, "", "ETICREIDASTA", 0, 0, 0, -13997);
  }

  private void PAN_INFODISPPROV_InitQueries()
  {
    StringBuffer SQL;

    PAN_INFODISPPROV.SetSize(MyGlb.OBJ_QUERY, 1);
    PAN_INFODISPPROV.SetIMDB(IMDB, "PQRY_PARAMETRI505", true);
    PAN_INFODISPPROV.set_SetString(MyGlb.MASTER_ROWNAME, "Record");
    PAN_INFODISPPROV.SetQueryIMDB(PPQRY_PARAMETRI505, IMDBDef17.PQRY_PARAMETRI505_RS, IMDBDef7.TBL_PARAMETRI501);
    JustLoaded = true;
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_VARPROVTOT, IMDBDef7.FLD_PARAMETRI501_PARVARPROTOT);
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_VARPROVPURO, IMDBDef7.FLD_PARAMETRI501_PARVARPROPUR);
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_VARPROVESI, IMDBDef7.FLD_PARAMETRI501_PARVARPROESI);
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_VARPROVSTN, IMDBDef7.FLD_PARAMETRI501_PARVARPROSTN);
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_VARPROVCASSA, IMDBDef7.FLD_PARAMETRI501_PARVARPROCAS);
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_STANZATTTOT, IMDBDef7.FLD_PARAMETRI501_PARSTAATTOPR);
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_STANZATTPURO, IMDBDef7.FLD_PARAMETRI501_PARSTAATPUPR);
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_STANZATTESI, IMDBDef7.FLD_PARAMETRI501_PARSTAATESPR);
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_STANZATTSTN, IMDBDef7.FLD_PARAMETRI501_PARSTAATSTPR);
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_STANZATTCASS, IMDBDef7.FLD_PARAMETRI501_PARSTAATCAPR);
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_DISPTOT, IMDBDef7.FLD_PARAMETRI501_PARDISTOTPRO);
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_SUREISCRIZIO, IMDBDef7.FLD_PARAMETRI501_PARDISPURPRO);
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_DISPESI, IMDBDef7.FLD_PARAMETRI501_PARDISESIPRO);
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_DISPSTN, IMDBDef7.FLD_PARAMETRI501_PARDISSTNPRO);
    PAN_INFODISPPROV.SetFieldPrimaryIndex(PFL_INFODISPPROV_DISPCASSA, IMDBDef7.FLD_PARAMETRI501_PARDISCASPRO);
    PAN_INFODISPPROV.SetMasterTable(0, "PARAMETRI501");
    //
    // Rieseguo la query se il pannello era già in stato DATA
    if (PAN_INFODISPPROV.Status() == 2)
    {
      int oldListQBE = PAN_INFODISPPROV.iUseListQBE;
      PAN_INFODISPPROV.iUseListQBE = 0;
      PAN_INFODISPPROV.PanelCommand(Glb.PCM_SEARCH);
      PAN_INFODISPPROV.PanelCommand(Glb.PCM_FIND);
      PAN_INFODISPPROV.iUseListQBE = oldListQBE;
    }
  }

  
  
  // **********************************************
  // Panel events dispatching
  // **********************************************
  public void ValidateCell(IDPanel SrcObj, IDVariant ColIndex, IDVariant CellModified , IDVariant Cancel, IDVariant FldWasModified, IDVariant RowWasModified, IDVariant IsInsert)
  {
    if (SrcObj == PAN_INFODISPPROV) PAN_INFODISPPROV_ValidateCell(ColIndex, CellModified , Cancel, FldWasModified, RowWasModified, IsInsert);
  }
  
  public void ValidateRow(IDPanel SrcObj, IDVariant Cancel)
  {
    if (SrcObj == PAN_INFODISPPROV) PAN_INFODISPPROV_ValidateRow(Cancel);
  }
  
  public void DynamicProperties(IDPanel SrcObj)
  {
    if (SrcObj == PAN_INFODISPPROV) PAN_INFODISPPROV_DynamicProperties();
  }
  
  public void CellActivated(IDPanel SrcObj, IDVariant ColIndex, IDVariant Cancel)
  {
    if (SrcObj == PAN_INFODISPPROV) PAN_INFODISPPROV_CellActivated(ColIndex, Cancel);
  }
  
  public void OnChangePage(IDPanel SrcObj, IDVariant NewPage, IDVariant Cancel)
  {
  }
  
  public void OnChangeLayout(IDPanel SrcObj, IDVariant NewLayout, IDVariant Cancel)
  {
  }
  
  public void OnChangeRow(IDPanel SrcObj)
  {
  }

  public void OnSelectingRow(IDPanel SrcObj)
  {
  }

  public void OnSorting(IDPanel SrcObj, IDVariant FldIdx, IDVariant Cancel)
  {
  }

  public void OnChangeSelection(IDPanel SrcObj, IDVariant NewVal, IDVariant Final, IDVariant Cancel)
  {
  }
  
  public void OnChangeLocking(IDPanel SrcObj, IDVariant NewLocking, IDVariant Cancel)
  {
  }
  
  public void OnChangeStatus(IDPanel SrcObj, IDVariant OldStatus)
  {
  }
  
  public void OnPanelCommand(IDPanel SrcObj, IDVariant Command, IDVariant Cancel, IDVariant UserOp)
  {
  }
  
  public void BeforeFind(IDPanel SrcObj, IDVariant Cancel)
  {
  }
  
  public void BeforeInsert(IDPanel SrcObj, IDVariant Cancel)
  {
  }
  
  public void BeforeUpdate(IDPanel SrcObj, IDVariant Cancel)
  {
  }

  public void BeforeBlobUpdate(IDPanel SrcObj, IDVariant Cancel, IDVariant Column, IDVariant Size, IDVariant Extension, IDVariant FilePath)
  {
  }
  
  public void BeforeDelete(IDPanel SrcObj, IDVariant Cancel)
  {
  }
  
  public void AfterInsert(IDPanel SrcObj)
  {
  }
  
  public void AfterUpdate(IDPanel SrcObj)
  {
  }

  public void AfterBlobUpdate(IDPanel SrcObj, IDVariant Column, IDVariant Size, IDVariant Extension)
  {
  }
  
  public void AfterDelete(IDPanel SrcObj)
  {
  }    

  public void AfterFind(IDPanel SrcObj, IDVariant CmdFind)
  {
  }    

  public void BeforeCommit(IDPanel SrcObj, IDVariant Cancel)
  {
  }
  
  public void AfterCommit(IDPanel SrcObj, IDVariant RowUpdated, IDVariant RowError)
  {
  }  

  public void OnDBError(IDPanel SrcObj, IDVariant Cancel, IDVariant Skip, IDVariant ErrNum, IDVariant ErrMsg, IDVariant NativeErrNum, IDVariant PanOp, IDDocument Doc)
  {
    if (SrcObj == PAN_INFODISPPROV) PAN_INFODISPPROV_OnDBError(Cancel, Skip, ErrNum, ErrMsg, NativeErrNum, PanOp, Doc);
  }  
  
  public void OnDownloadBlob(IDPanel SrcObj, IDVariant Cancel, IDVariant Column, IDVariant Size, IDVariant Extension, IDVariant Inline, IDVariant Filename, IDVariant MimeType)
  {
  }

  public void OnPrint(IDPanel SrcObj, IDVariant Cancel, IDVariant Dest, IDVariant SetWC)
  {
  }  
    
  public void TabClick(OTabView SrcObj, IDVariant PreviousPage, IDVariant Cancel)
  {
  }    

  public void NodeClick(ATree SrcObj, ATreeNode Node)
  {
  }    

  public void OnTreeDropNode(ATree SrcObj, IDVariant SourceHash, IDVariant SourceTreeIndex, IDVariant DestinationHash, IDVariant ShiftKey, IDVariant AltKey, IDVariant ControlKey)
  {
  }    

  public void OnTreeExpandNode(ATree SrcObj, IDVariant HashKey, IDVariant Cancel)
  {
  }
  
  public void OnTreeActivateNode(ATree SrcObj, IDVariant HashKey, IDVariant Cancel)
  {
  }

  public void OnTreeChangeSelNode(ATree SrcObj, IDVariant HashKey, IDVariant Selected, IDVariant Cancel, IDVariant Final)
  {
  }
  
  public void OnTreeDropDoc(ATree SrcObj, IDDocument SourceDoc, IDDocument DestDoc, IDVariant ShiftKey, IDVariant AltKey, IDVariant ControlKey, IDVariant Cancel)
  {
  }    

  public void OnTreeExpandDoc(ATree SrcObj, IDDocument Doc, IDVariant Cancel)
  {
  }
  
  public void OnTreeActivateDoc(ATree SrcObj, IDDocument Doc, IDVariant Cancel)
  {
  }
  
  public void OnTreeChangeSelDoc(ATree SrcObj, IDDocument Doc, IDVariant Selected, IDVariant Cancel, IDVariant Final)
  {
  }
  
  public void OnFormattingSection(OBook SrcObj, int SectionID)
  {
  }

  public void OnAfterFormattingSection(OBook SrcObj, int SectionID)
  {
  }

  public void OnFormattingPage(OBook SrcObj, int PageID)
  {
  }

  public void OnChangingSpan(OBook SrcObj, int SpanIdx, IDVariant OldVal, IDVariant NewVal, IDVariant Cancel)
  {
  }

  public void OnBoxDrop(OBook SrcObj, IDVariant SrcBoxIdx, IDVariant DstBoxIdx)
  {
  }

  public void OnBoxTransform(OBook SrcObj, IDVariant BoxIdx, IDVariant NewX, IDVariant NewY, IDVariant NewW, IDVariant NewH, IDVariant Cancel)
  {
  }

  public void OnConnecting(OBook SrcObj, IDConnection DBConn)
  {
  }

  public void Activated(OBook SrcObj, int ObjID, String BoxName)
  {
  }

  public void OnIMDBUpdate(OBook SrcObj, int ReportIdx)
  {
  }

  public void OnPreview(OBook SrcObj)
  {
  }
  
  public void OnOpenPopup(ACommand SrcObj, IDVariant Direction, IDVariant Cancel) 
  {
  }
  
  public void OnCmdSetCommand(ACommand SrcObj, IDVariant CmdIdx, IDVariant ChildIdx, IDVariant Cancel) 
  {
  }
  
  public void OnCmdSetGeneralDrag(ACommand SrcObj, IDVariant DragInfo, IDVariant CmdIdx, IDVariant ChildIdx)
  {
  }
  
  public void OnCmdSetGeneralDrop(ACommand SrcObj, IDVariant DragInfo, IDVariant CmdIdx, IDVariant ChildIdx)
  {
  }

  public void OnChangeCollapse(WebFrame SrcObj, IDVariant Collapse, IDVariant Cancel)
  {
  }

  public void OnGraphClick(WebFrame SrcObj, IDVariant NumSerie, IDVariant NumPoint)
  {
  }

  public void OnGraphOptions(WebFrame SrcObj, IDVariant Options)
  {
  }
  
  public void OnRenderToolbar(WebFrame SrcObj, IDVariant CmdIdx, IDVariant Visible)
  {
  }

  public void OnBookCommand(OBook SrcObj, IDVariant Command, IDVariant Cancel, IDVariant UserOp)
  {
  }

  public void OnCmdSetChangeExpand(ACommand SrcObj, IDVariant Expand, IDVariant Cancel)
  {
  }

  public void OnTreeChangeExpandNode(ATree SrcObj, IDVariant HashKey, IDVariant Expanded, IDVariant Cancel)
  {
  }

  public void OnTreeChangeExpandDoc(ATree SrcObj, IDDocument Doc, IDVariant Expanded, IDVariant Cancel)
  {
  }
  

  public void OnMouseClick(IDPanel SrcObj, IDVariant btn, IDVariant x, IDVariant y, IDVariant xb, IDVariant yb, IDVariant c, IDVariant r, IDVariant cancel)
  {
  }

  public void OnMouseDoubleClick(IDPanel SrcObj, IDVariant btn, IDVariant x, IDVariant y, IDVariant xb, IDVariant yb, IDVariant c, IDVariant r, IDVariant cancel)
  {
  }
  
  public void OnMouseClick(OBook SrcObj, IDVariant btn, IDVariant x, IDVariant y, IDVariant xb, IDVariant yb, IDVariant boxid, IDVariant cancel)
  {
  }

  public void OnMouseDoubleClick(OBook SrcObj, IDVariant btn, IDVariant x, IDVariant y, IDVariant xb, IDVariant yb, IDVariant boxid, IDVariant cancel)
  {
  }
  
  public void OnMouseClick(ATree SrcObj, IDVariant btn, IDVariant x, IDVariant y, IDVariant xb, IDVariant yb, IDVariant nodehash, IDDocument doc, IDVariant cancel)
  {
  }

  public void OnMouseDoubleClick(ATree SrcObj, IDVariant btn, IDVariant x, IDVariant y, IDVariant xb, IDVariant yb, IDVariant nodehash, IDDocument doc, IDVariant cancel)
  {
  }
  
  public void OnMouseClick(AGraph SrcObj, IDVariant btn, IDVariant x, IDVariant y, IDVariant xb, IDVariant yb, IDVariant numserie, IDVariant recordselected, IDVariant cancel)
  {
  }

  public void OnMouseDoubleClick(AGraph SrcObj, IDVariant btn, IDVariant x, IDVariant y, IDVariant xb, IDVariant yb, IDVariant numserie, IDVariant recordselected, IDVariant cancel)
  {
  }
  
  public void OnMouseClick(OTabView SrcObj, IDVariant btn, IDVariant x, IDVariant y, IDVariant xb, IDVariant yb, IDVariant tabid, IDVariant cancel)
  {
  }

  public void OnMouseDoubleClick(OTabView SrcObj, IDVariant btn, IDVariant x, IDVariant y, IDVariant xb, IDVariant yb, IDVariant tabid, IDVariant cancel)
  {
  }  
  
  public void OnReorderColum(IDPanel SrcObj, IDVariant sourcefield, IDVariant targetfield)
  {
  }
  
  public void OnResizeColum(IDPanel SrcObj, IDVariant sourcefield, IDVariant oldwidth)
  {
  }
  

  public void OnGenericDrag(IDPanel SrcObj, IDVariant draginfo,  IDVariant button, IDVariant colidx)
  {
  }

  public void OnGenericDrop(IDPanel SrcObj, IDVariant draginfo, IDVariant cancel, IDVariant button, IDVariant x, IDVariant y, IDVariant xb, IDVariant yb, IDVariant colidx, IDVariant rownum, IDDocument doc)
  {
  }
  
  public void OnGenericDrag(ATree SrcObj, IDVariant draginfo,  IDVariant button, IDVariant hashkey)
  {
  }

  public void OnGenericDrop(ATree SrcObj, IDVariant draginfo, IDVariant cancel, IDVariant button, IDVariant x, IDVariant y, IDVariant xb, IDVariant yb, IDVariant hashkey, IDDocument doc)
  {
  }  
  
  public void OnGenericDrag(OBook SrcObj, IDVariant draginfo,  IDVariant button, IDVariant boxid)
  {
  }

  public void OnGenericDrop(OBook SrcObj, IDVariant draginfo, IDVariant cancel, IDVariant button, IDVariant x, IDVariant y, IDVariant xb, IDVariant yb, IDVariant boxid)
  {
  }    
  
  public void OnGenericDrag(OTabView SrcObj, IDVariant draginfo, IDVariant button, IDVariant pageindex)
  {
  }

  public void OnGenericDrop(OTabView SrcObj, IDVariant draginfo, IDVariant cancel, IDVariant button, IDVariant x, IDVariant y, IDVariant xb, IDVariant yb, IDVariant pageindex)
  {
  }

  public void OnExpandingGroup(IDPanel SrcObj, IDVariant expanded, IDVariant userOperation)
  {
  }  

  public void OnChangeGroupCollapse(IDPanel SrcObj, IDVariant GrpIndex)
  {
  }
  
  public void OnShowMultipleSelection(IDPanel SrcObj, IDVariant NewValue, IDVariant Cancel, IDVariant UserOperation)
  {
  }
  
  public void OnChangeTextSelection(IDPanel SrcObj, IDVariant Field, IDVariant OldSelectionStart, IDVariant OldSelectionEnd)
  {
  }
  
  public void OnFocus(IDPanel SrcObj, IDVariant Field, IDVariant GotFocus)
  {
  }
  
  public void OnFrameKeyPress(WebFrame SrcObj, IDVariant KeySet, IDVariant KeyCode, IDVariant Skip)
  {
  }
  
  public void OnGetLKE(IDPanel SrcObj, IDCachedRowSet RS, IDVariant ntry, IDVariant nullv, IDVariant bskip, IDVariant bcancel, IDVariant fldindex)
  {
  }
  
  public void OnMouseOver(IDPanel SrcObj, IDVariant Field, IDVariant Row)
  {
  }
  
  public void OnFieldListVisibilityChanged(IDPanel SrcObj, IDVariant FieldIndex, IDVariant NewValue, IDVariant Final)
  {
  }
}
